name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snk

      - name: Generate Snake Game from commits
        run: snk generate --user AndersonDalMagro --output ./snake.svg

      - name: Push Snake Game to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: snake.svg
